### ISSUE TITLE
TypeError: gridplot() got an unexpected keyword argument 'plot_width'

### ISSUE THREAD

**Issue by BartoszDombrow** [wdecoster/nanoQC#17]
Hello,

I have an error:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/bin/nanoQC", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/nanoQC/nanoQC.py", line 43, in main
    save(gridplot(children=[[hist], seq_plots, qual_plots],
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: gridplot() got an unexpected keyword argument 'plot_width'

Could you please help me with that issue?

Python 3.12.1
nanoQC 0.9.4

**Comment by weronikajaskowiak** [comment]
Hello, 
I have also encountered this problem, Python 2.7.18 and NanoQC 0.9.4
I would appreciate your help.

**Comment by anita-brzoza** [comment]
Hi, I have the same issue with python 3.8 and NanoQC 0.9.4

**Comment by pelutz** [comment]
Same error here:

Traceback (most recent call last):
  File "/home2020/home/inci/plutz/miniforge3/envs/nanoqc/bin/nanoQC", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home2020/home/inci/plutz/miniforge3/envs/nanoqc/lib/python3.12/site-packages/nanoQC/nanoQC.py", line 43, in main
    save(gridplot(children=[[hist], seq_plots, qual_plots],
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: gridplot() got an unexpected keyword argument 'plot_width'

The NanoQC.log indicated:
2024-09-08 21:27:10,217 NanoQC started.
2024-09-08 22:06:44,937 Extracting nucleotides and quality scores.
2024-09-08 22:54:07,539 Using 4280008 reads with a minimum length of 200bp for plotting
2024-09-08 22:54:07,540 Creating plots...
2024-09-08 22:59:29,158 Per base sequence content and quality completed.

I had installed nanoqc 0.9.4 in a Conda environment using pip (installation did not work via bioconda), along with python 3.12.5 and bokeh 3.0.0, on a Red Hat linux server. Since apparently plot_width has been replaced by width as of bokeh 3.0.0, I tried to downgrade bokeh to v2.4.3, but got another (much earlier) error:

Traceback (most recent call last):
  File "/home2020/home/inci/plutz/miniforge3/envs/nanoqc/bin/nanoQC", line 5, in <module>
    from nanoQC.nanoQC import main
  File "/home2020/home/inci/plutz/miniforge3/envs/nanoqc/lib/python3.12/site-packages/nanoQC/nanoQC.py", line 10, in <module>
    from bokeh.plotting import figure, save, output_file
  File "/home2020/home/inci/plutz/miniforge3/envs/nanoqc/lib/python3.12/site-packages/bokeh/plotting/__init__.py", line 22, in <module>
    from . import figure as _figure ; _figure
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home2020/home/inci/plutz/miniforge3/envs/nanoqc/lib/python3.12/site-packages/bokeh/plotting/figure.py", line 25, in <module>
    from ..core.properties import (
  File "/home2020/home/inci/plutz/miniforge3/envs/nanoqc/lib/python3.12/site-packages/bokeh/core/properties.py", line 273, in <module>
    from .property.auto import Auto; Auto
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home2020/home/inci/plutz/miniforge3/envs/nanoqc/lib/python3.12/site-packages/bokeh/core/property/auto.py", line 24, in <module>
    from .enum import Enum
  File "/home2020/home/inci/plutz/miniforge3/envs/nanoqc/lib/python3.12/site-packages/bokeh/core/property/enum.py", line 27, in <module>
    from .primitive import String
  File "/home2020/home/inci/plutz/miniforge3/envs/nanoqc/lib/python3.12/site-packages/bokeh/core/property/primitive.py", line 37, in <module>
    bokeh_bool_types += (np.bool8,)
                         ^^^^^^^^
  File "/home2020/home/inci/plutz/miniforge3/envs/nanoqc/lib/python3.12/site-packages/numpy/__init__.py", line 414, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'bool8'. Did you mean: 'bool'?

Thanks in advance for your help,
Best,
PE

**Comment by jtamames** [comment]
Same here. Anybody there caring about issues?

**Comment by wdecoster** [comment]
Thank you for your patience. This should be solved in v0.10.0!
