### ISSUE TITLE
FASTQ read-in issue

### ISSUE THREAD

**Issue by damioresegun** [wdecoster/nanoQC#2]
Hi, 
I am trying to run nanoqc however, it is giving me the error below. I have tried using fastq files made natively by both minKNOW/Albacore and Poretools. Both are giving me the error:

nanoQC --outdir ./ ~/Documents/Alba_FastQs/fastq_runid_3633b18cae0dfdf457c8ebe23539fd8c83e63fe0_0.fastq
Traceback (most recent call last):
  File "/usr/local/bin/nanoQC", line 9, in <module>
    load_entry_point('nanoQC==0.4.3', 'console_scripts', 'nanoQC')()
  File "/usr/local/lib/python2.7/dist-packages/nanoQC/nanoQC.py", line 44, in main
    name=os.path.join(args.outdir, "SequenceLengthDistribution.png"))
  File "/usr/local/lib/python2.7/dist-packages/nanoQC/nanoQC.py", line 90, in LengthHistogram
    lengths = getLengths(fqin)
  File "/usr/local/lib/python2.7/dist-packages/nanoQC/nanoQC.py", line 82, in getLengths
    return np.array([len(record) for record in SeqIO.parse(fastq, "fastq")])
  File "/usr/local/lib/python2.7/dist-packages/Bio/SeqIO/__init__.py", line 611, in parse
    for r in i:
  File "/usr/local/lib/python2.7/dist-packages/Bio/SeqIO/QualityIO.py", line 1033, in FastqPhredIterator
    for title_line, seq_string, quality_string in FastqGeneralIterator(handle):
  File "/usr/local/lib/python2.7/dist-packages/Bio/SeqIO/QualityIO.py", line 897, in FastqGeneralIterator
    line = handle_readline()
  File "/usr/lib/python2.7/gzip.py", line 455, in readline
    c = self.read(readsize)
  File "/usr/lib/python2.7/gzip.py", line 261, in read
    self._read(readsize)
  File "/usr/lib/python2.7/gzip.py", line 296, in _read
    self._read_gzip_header()
  File "/usr/lib/python2.7/gzip.py", line 190, in _read_gzip_header
    raise IOError, 'Not a gzipped file'
IOError: Not a gzipped file

I also tried zipping the file which resulted in the error:
 nanoQC --outdir ./ ~/Documents/Pore_FastQs/allFastQ_adapterRemoved.fastq.gz                      Traceback (most recent call last):
  File "/usr/local/bin/nanoQC", line 9, in <module>
    load_entry_point('nanoQC==0.4.3', 'console_scripts', 'nanoQC')()
  File "/usr/local/lib/python2.7/dist-packages/nanoQC/nanoQC.py", line 44, in main
    name=os.path.join(args.outdir, "SequenceLengthDistribution.png"))
  File "/usr/local/lib/python2.7/dist-packages/nanoQC/nanoQC.py", line 91, in LengthHistogram
    plt.hist(lengths, bins='auto')
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 2989, in hist
    ax = gca()
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 959, in gca
    return gcf().gca(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 588, in gcf
    return figure()
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 534, in figure
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backend_bases.py", line 170, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backend_bases.py", line 176, in new_figure_manager_given_figure
    canvas = cls.FigureCanvas(figure)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_qt5agg.py", line 35, in __init__
    super(FigureCanvasQTAggBase, self).__init__(figure=figure)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_qt5.py", line 171, in wrapper
    __init__(self, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_qt5.py", line 235, in __init__
    _create_qApp()
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_qt5.py", line 122, in _create_qApp
    raise RuntimeError('Invalid DISPLAY variable')
RuntimeError: Invalid DISPLAY variable

I'm not sure whether this is a formatting issue with the fastq files or an issue with nanoQC itself. Help?

**Comment by wdecoster** [comment]
Indeed, the script expects gzipped files, so that explains your first error. The cause of the second error is that your server doesn't have X activated for graphical applications, or you logged in using ssh instead of `ssh -X`. But no worries, that's something I can fix in the script. I'll push a new version in a bit.

**Comment by wdecoster** [comment]
Should be fixed in nanoQC 0.5.0. Please let me know if you encounter other issues or have suggestions/feature requests!

**Comment by damioresegun** [comment]
That solved it. Thanks for the help!

**Comment by jamesdalg** [comment]
Suggestion: add an option to use ubam for nanoQC.

**Comment by wdecoster** [comment]
Happy to get pull requests for that.
