### ISSUE TITLE
Unable to run nanoQC

### ISSUE THREAD

**Issue by wyzhangMPI** [wdecoster/nanoQC#4]
Hi,
    I am trying to use nanoQC for the Quality check of fastq data from nanopore sequencing, however, I got errors when running the program:
$ nanoQC ./Mouse_Rapid_1st.fq --outdir ./ -f pdf

> Traceback (most recent call last):
  File "/home/wyzhang/opt/biosoftware/miniconda2/bin/nanoQC", line 11, in <module>
    sys.exit(main())
  File "/home/wyzhang/opt/biosoftware/miniconda2/lib/python2.7/site-packages/nanoQC/nanoQC.py", line 46, in main
    name=os.path.join(args.outdir, "SequenceLengthDistribution.png"))
  File "/home/wyzhang/opt/biosoftware/miniconda2/lib/python2.7/site-packages/nanoQC/nanoQC.py", line 93, in length_histogram
    lengths = get_lengths(fqin)
  File "/home/wyzhang/opt/biosoftware/miniconda2/lib/python2.7/site-packages/nanoQC/nanoQC.py", line 85, in get_lengths
    return np.array([len(record) for record in SeqIO.parse(fastq, "fastq")])
  File "/home/wyzhang/opt/biosoftware/miniconda2/lib/python2.7/site-packages/Bio/SeqIO/__init__.py", line 591, in parse
    for r in i:
  File "/home/wyzhang/opt/biosoftware/miniconda2/lib/python2.7/site-packages/Bio/SeqIO/QualityIO.py", line 1033, in FastqPhredIterator
    for title_line, seq_string, quality_string in FastqGeneralIterator(handle):
  File "/home/wyzhang/opt/biosoftware/miniconda2/lib/python2.7/site-packages/Bio/SeqIO/QualityIO.py", line 896, in FastqGeneralIterator
    line = handle_readline()
  File "/home/wyzhang/opt/biosoftware/miniconda2/lib/python2.7/gzip.py", line 464, in readline
    c = self.read(readsize)
  File "/home/wyzhang/opt/biosoftware/miniconda2/lib/python2.7/gzip.py", line 268, in read
    self._read(readsize)
  File "/home/wyzhang/opt/biosoftware/miniconda2/lib/python2.7/gzip.py", line 303, in _read
    self._read_gzip_header()
  File "/home/wyzhang/opt/biosoftware/miniconda2/lib/python2.7/gzip.py", line 197, in _read_gzip_header
    raise IOError, 'Not a gzipped file'
IOError: Not a gzipped file

Could you help to check what is going wrong there? Thanks!

Best,
Wenyu Zhang

**Comment by wdecoster** [comment]
Hi Wenyu Zhang,

Thanks for reporting this issue.

nanoQC expects a gzipped file (as you can read in the error message). The README wasn't very clear on that, so I have updated the usage. This should solve your error I believe. 
While .gz is probably the most used compression method, I agree that the current implementation of nanoQC is not very flexible and I should support other types of compression or uncompressed data.

Second, I see you are using the `-f` argument to specify an output format. I accidentally left this argument in there, but since nanoQC 0.6.0 all plots are generated in HTML format as shown in the example. Converting this to other formats is probably technically possible, but not implemented as such.
I just pushed nanoQC v0.7.0 to PyPI which no longer contains the confusing and useless `-f` argument.

Finally, I see you are using python2.7. This may work for nanoQC, but it's not guaranteed or tested. I write for Python3. For some of my other scripts, I'm sure you cannot use Python2.7.

Hope this helps.

Cheers,
Wouter

**Comment by wyzhangMPI** [comment]
Hi Wouter,
     Thanks for the quick reply.
     One more question, are you planning for nanoQC to check for the 
adapter info in the dataset? It seems the current version cannot give 
this info.


Best,
Wenyu

------ Original Message ------

**Comment by wdecoster** [comment]
Hi Wenyu,

That would indeed be a nice functionality. I'm not sure when I'll have the time to look at that, but I welcome contributions.

Cheers,
Wouter
